#############################################################################
# Makefile for building: TaskStalker
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Dec 21 11:45:24 2012
# Project:  TaskStalker.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile TaskStalker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		proc.cpp \
		visualiser.cpp \
		confirmkill.cpp \
		info.cpp \
		simulator.cpp \
		simulatorinit.cpp \
		sys.cpp \
		settings.cpp moc_mainwindow.cpp \
		moc_visualiser.cpp \
		moc_confirmkill.cpp \
		moc_info.cpp \
		moc_simulator.cpp \
		moc_simulatorinit.cpp \
		moc_settings.cpp \
		qrc_images.cpp \
		qrc_help.cpp
OBJECTS       = main.o \
		mainwindow.o \
		proc.o \
		visualiser.o \
		confirmkill.o \
		info.o \
		simulator.o \
		simulatorinit.o \
		sys.o \
		settings.o \
		moc_mainwindow.o \
		moc_visualiser.o \
		moc_confirmkill.o \
		moc_info.o \
		moc_simulator.o \
		moc_simulatorinit.o \
		moc_settings.o \
		qrc_images.o \
		qrc_help.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TaskStalker.pro
QMAKE_TARGET  = TaskStalker
DESTDIR       = 
TARGET        = TaskStalker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_visualiser.h ui_confirmkill.h ui_info.h ui_simulator.h ui_simulatorinit.h ui_settings.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TaskStalker.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile TaskStalker.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile TaskStalker.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TaskStalker1.0.0 || $(MKDIR) .tmp/TaskStalker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TaskStalker1.0.0/ && $(COPY_FILE) --parents mainwindow.h proc.h visualiser.h confirmkill.h info.h simulator.h simulatorinit.h sys.h settings.h .tmp/TaskStalker1.0.0/ && $(COPY_FILE) --parents images.qrc help.qrc .tmp/TaskStalker1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp proc.cpp visualiser.cpp confirmkill.cpp info.cpp simulator.cpp simulatorinit.cpp sys.cpp settings.cpp .tmp/TaskStalker1.0.0/ && $(COPY_FILE) --parents mainwindow.ui visualiser.ui confirmkill.ui info.ui simulator.ui simulatorinit.ui settings.ui .tmp/TaskStalker1.0.0/ && (cd `dirname .tmp/TaskStalker1.0.0` && $(TAR) TaskStalker1.0.0.tar TaskStalker1.0.0 && $(COMPRESS) TaskStalker1.0.0.tar) && $(MOVE) `dirname .tmp/TaskStalker1.0.0`/TaskStalker1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TaskStalker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_visualiser.cpp moc_confirmkill.cpp moc_info.cpp moc_simulator.cpp moc_simulatorinit.cpp moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_visualiser.cpp moc_confirmkill.cpp moc_info.cpp moc_simulator.cpp moc_simulatorinit.cpp moc_settings.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_visualiser.cpp: visualiser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) visualiser.h -o moc_visualiser.cpp

moc_confirmkill.cpp: confirmkill.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) confirmkill.h -o moc_confirmkill.cpp

moc_info.cpp: info.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) info.h -o moc_info.cpp

moc_simulator.cpp: simulator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) simulator.h -o moc_simulator.cpp

moc_simulatorinit.cpp: simulatorinit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) simulatorinit.h -o moc_simulatorinit.cpp

moc_settings.cpp: settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

compiler_rcc_make_all: qrc_images.cpp qrc_help.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp qrc_help.cpp
qrc_images.cpp: images.qrc \
		img/button_pause.png \
		img/button_play.png \
		img/logo.png \
		img/uninterruptible.png \
		img/unknown.png \
		img/ready.png \
		img/stopped.png \
		img/interruptible.png \
		img/zombie.png \
		img/executing.png \
		img/running.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

qrc_help.cpp: help.qrc \
		doc/help.qch \
		doc/index.html \
		doc/mainwindow.png \
		doc/main.html \
		doc/info.html \
		doc/collection.qhc \
		doc/viswindow.png \
		doc/visualisation.html
	/usr/bin/rcc -name help help.qrc -o qrc_help.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_visualiser.h ui_confirmkill.h ui_info.h ui_simulator.h ui_simulatorinit.h ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_visualiser.h ui_confirmkill.h ui_info.h ui_simulator.h ui_simulatorinit.h ui_settings.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_visualiser.h: visualiser.ui
	/usr/bin/uic-qt4 visualiser.ui -o ui_visualiser.h

ui_confirmkill.h: confirmkill.ui
	/usr/bin/uic-qt4 confirmkill.ui -o ui_confirmkill.h

ui_info.h: info.ui
	/usr/bin/uic-qt4 info.ui -o ui_info.h

ui_simulator.h: simulator.ui
	/usr/bin/uic-qt4 simulator.ui -o ui_simulator.h

ui_simulatorinit.h: simulatorinit.ui
	/usr/bin/uic-qt4 simulatorinit.ui -o ui_simulatorinit.h

ui_settings.h: settings.ui
	/usr/bin/uic-qt4 settings.ui -o ui_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		sys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		proc.h \
		visualiser.h \
		info.h \
		simulatorinit.h \
		sys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

proc.o: proc.cpp proc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proc.o proc.cpp

visualiser.o: visualiser.cpp visualiser.h \
		ui_visualiser.h \
		proc.h \
		confirmkill.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualiser.o visualiser.cpp

confirmkill.o: confirmkill.cpp confirmkill.h \
		ui_confirmkill.h \
		visualiser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confirmkill.o confirmkill.cpp

info.o: info.cpp info.h \
		ui_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o info.o info.cpp

simulator.o: simulator.cpp simulator.h \
		ui_simulator.h \
		proc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulator.o simulator.cpp

simulatorinit.o: simulatorinit.cpp simulatorinit.h \
		ui_simulatorinit.h \
		simulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulatorinit.o simulatorinit.cpp

sys.o: sys.cpp sys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sys.o sys.cpp

settings.o: settings.cpp settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_visualiser.o: moc_visualiser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_visualiser.o moc_visualiser.cpp

moc_confirmkill.o: moc_confirmkill.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_confirmkill.o moc_confirmkill.cpp

moc_info.o: moc_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_info.o moc_info.cpp

moc_simulator.o: moc_simulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simulator.o moc_simulator.cpp

moc_simulatorinit.o: moc_simulatorinit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simulatorinit.o moc_simulatorinit.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

qrc_help.o: qrc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_help.o qrc_help.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

